export default {
	HOME: "/",
	SUITE: "/suite",
	REGISTER: "/suite/register",
	LOGIN: "/suite/login",
	ASSISTANTS: "/suite/assistants",
	INVOICES: "/suite/invoices",
	ACCOUNT: "/suite/account",
	ABOUT_YOU: "/suite/about-you",
	COMMUNICATION: "/suite/communication-preferences",
	PAYMENT_METHODS: "/suite/payment-methods",
	ADD_PAYMENT_METHOD: "/suite/add-payment-method",
	ADD_PAYMENT_METHOD_CONFIRMATION: "/suite/add-payment-method-confirmation",
	RESET_PASSWORD: "/suite/reset-password",
	RESET_PASSWORD_CONFIRMATION: "/suite/reset-password-confirmation",
	ASSISTANT_ACTIONS: "/suite/assistant-actions",
	ASSISTANT_SUITE: "/assistant-suite",
	ASSISTANT_REGISTER: "/assistant-register",
};
