export const industries = [
  {
    name: 'ENTREPRENEURS',
    slug: 'entrepreneurs',
    logo: 'industries/Logo-Entrepeneurs.png',
    logoAlt: 'Logo Entrepeneurs',
    img: '',
    imgAlt: '',
    subtitle: "Iconic Assistants' Virtual Professionals are essential partners for entrepreneurs. Specializing in executive administration, digital marketing, and project management, our VAs provide the support needed for strategic growth. Choose Iconic Assistants to empower your business with efficient and tailored assistance.",
    description: "VAs work as your executive assistant, project manager, and head recruiter.",
  },
  {
    name: 'LAW FIRMS',
    slug: 'law-firms',
    logo: 'industries/Logo-Law-Firms.png',
    logoAlt: 'Logo Law Firms',
    img: '',
    imgAlt: '',
    subtitle: "In the legal field, Iconic Assistants' Virtual Professionals redefine support. Expertise in administrative tasks, data entry, customer service, and project management makes our VAs an invaluable asset. Optimize your legal practice with Iconic Assistants' VAs for efficient and dedicated assistance.",
    description: "VAs help collect & organize documents, prepare letters, manage cases, etc.",
  },
  {
    name: 'MARKETING AGENCIES',
    slug: 'marketing-agencies',
    logo: 'industries/Logo-Marketing.png',
    logoAlt: 'Logo Marketing',
    img: '',
    imgAlt: '',
    subtitle: "In the fast-paced marketing industry, Iconic Assistants' Virtual Professionals are the secret to streamlined success. Our VAs specialize in social media management, digital marketing, data entry, and expert customer service. Choose Iconic Assistants for a dynamic team that elevates your marketing strategies and enhances client engagement.",
    description: "VAs who create content, emails, AD campaigns, branding, websites, etc.",
  },
  {
    name: 'MEDICAL & HEALTHCARE',
    slug: 'medical-healthcare',
    logo: 'industries/Logo-Medical-Healthcare.png',
    logoAlt: 'Logo Medical & Healthcare',
    img: '',
    imgAlt: '',
    subtitle: "Iconic Assistants' Virtual Professionals redefine efficiency in healthcare, seamlessly managing appointments, ensuring accurate data entry, and providing essential administrative support. Elevate patient care by choosing our VAs for streamlined and impactful healthcare operations.",
    description: "VAs book doctors' appointments, data entry, marketing, sales, translate documents, etc.",
  },
  {
    name: 'NON-PROFITS',
    slug: 'non-profits',
    logo: 'industries/Logo-Non-Profit.png',
    logoAlt: 'Logo Non-Profit',
    img: '',
    imgAlt: '',
    subtitle: "In the non-profit sector, Iconic Assistants' Virtual Professionals shine in administrative support, donor database management, and impactful social media engagement. Elevate your non-profit's efficiency and focus on your mission with our dedicated VAs.",
    description: "VAs outreach to donors, manage fundraisers, create marketing collateral, etc.",
  },
  {
    name: 'PROPERTY MANAGEMENT',
    slug: 'property-management',
    logo: 'industries/Logo-Property-Management.png',
    logoAlt: 'Logo Property Management',
    img: '',
    imgAlt: '',
    subtitle: "For seamless property management, trust Iconic Assistants' Virtual Professionals. Specializing in administrative tasks, customer service, data entry, and project management, our VAs optimize workflows. Choose Iconic Assistants for a tailored and efficient support team in property management.",
    description: "VAs manage contractors, schedule appointments, manage new leads, etc.",
  },
  {
    name: 'REAL ESTATE',
    slug: 'real-estate',
    logo: 'industries/Logo-Real-Estate.png',
    logoAlt: 'Logo Real Estate',
    img: '',
    imgAlt: '',
    subtitle: "In real estate, Iconic Assistants' Virtual Professionals redefine efficiency. From appointment setting and data entry to customer service and sales support, our VAs streamline operations. Choose Iconic Assistants for a dynamic and dedicated team that enhances your real estate endeavors.",
    description: "VAs schedule viewings, manage documents, offer customers support, etc.",
  },
  {
    name: 'RETAILERS & WHOLESALERS',
    slug: 'retailers-wholesalers',
    logo: 'industries/Logo-Retail-Wholesale.png',
    logoAlt: 'Logo Retail & Wholesale',
    img: '',
    imgAlt: '',
    subtitle: "In the non-profit sector, Iconic Assistants' Virtual Professionals shine in administrative support, donor database management, and impactful social media engagement. Elevate your non-profit's efficiency and focus on your mission with our dedicated VAs.",
    description: "VAs outreach to donors, manage fundraisers, create marketing collateral, etc.",
  },
  {
    name: 'TECH & SOFTWARE',
    slug: 'tech-software',
    logo: 'industries/Logo-Tech-Software.png',
    logoAlt: 'Logo Tech & Software',
    img: '',
    imgAlt: '',
    subtitle: "In the tech and software industry, Iconic Assistants' Virtual Professionals are your efficiency partners. Specializing in project management, data entry, customer service, and administrative tasks, our VAs seamlessly integrate into your operations. Optimize your workflow with Iconic Assistants' VAs for a tech-savvy and adaptable support team.",
    description: "VAs lead onboardings, offers customer support, manage client success, etc.",
  },
];

export const services = [];